_target_: torch.optim.RMSprop
lr: ${lr}     # (default: 1e-2)
momentum: 0   # momentum factor (default: 0)
alpha: 0.99   # smoothing constant (default: 0.99)
eps: 1e-8
centered: True
weight_decay: ${weight_decay}
