#config/config.yaml

num_classes: 3
root: '/home/dataset/chexpert'
train_csv: '/home/dataset/chexpert/CheXpert-v1.0-pad224/train.csv'
valid_csv: '/home/dataset/chexpert/CheXpert-v1.0-pad224/valid.csv'
ckpt_name: 'best_saved.pth'
num_workers: 1
batch_size: 16
epochs: 5
scheduler: 'CosineAnnealingLR'
learning_rate: 1e-4
weight_decay: 1e-4