setup:
  project: ${project_name}
  name: ${now:%Y-%m-%d_%H-%M-%S}
  entity: snuh_interns
  mode: online
  dir: ${log_dir}/${hydra:job.override_dirname}

config:
  hparams_search: ${hparams_search.name}
  lr: ${lr}
  batch_size: ${batch_size}
  weight_decay: ${weight_decay}
  asl_gamma_neg: ${asl_gamma_neg}
  asl_ps_factor: ${asl_ps_factor}
  ra_num_ops: ${ra_num_ops}
  ra_magnitude: ${ra_magnitude}
  model: ${model.model_name}
  optimizer: ${optimizer._target_}
  loss: ${loss._target_}
  # conditional_train: ${conditional_train.execute_mode}

# watch:
#   log: all
#   log_freq: 500
