setup:
  project: ${project_name}
  name: ${now:%Y-%m-%d_%H-%M-%S}
  entity: snuh_interns
  mode: online
  dir: ${log_dir}/${hydra:job.override_dirname}

config:
  hparams_search: ${hparams_search.name}
  batch_size: ${batch_size}
  lr: ${lr}
  model: ${model.model_name}
  optimizer: ${optimizer._target_}
  loss: ${loss._target_}
  # conditional_train: ${conditional_train.execute_mode}

# watch:
#   log: all
#   log_freq: 500
