#https://github1s.com/facebookresearch/hydra/blob/main/examples/patterns/multi-select/
name: raytune

# should set in default
param_space:
  lr:
    _target_: ray.tune.loguniform
    lower: 0.00001
    upper: 0.1
  weight_decay:
    _target_: ray.tune.loguniform
    lower: 0.00001
    upper: 0.1
  batch_size:
    _target_: ray.tune.choice
    categories:
      - 128
      - 256
  asl_gamma_neg:
    _target_: ray.tune.uniform
    lower: 1
    upper: 5
  asl_ps_factor:
    _target_: ray.tune.uniform
    lower: 0.05
    upper: 0.25
  ra_num_ops:
    _target_: ray.tune.randint
    lower: 2
    upper: 14
  ra_magnitude:
    _target_: ray.tune.randint
    lower: 5
    upper: 20

### Tuner ####
tune_config:
  _target_: ray.tune.TuneConfig
  search_alg:
    _target_: ray.tune.search.hyperopt.HyperOptSearch
    metric: loss
    mode: min
    random_state_seed: 12345 # seed for reproducible results

  # scheduler:
  #   _target_: ray.tune.schedulers.ASHAScheduler
  #   metric: loss
  #   mode: min
  #   grace_period: 5

  num_samples: ${num_samples}

run_config:
  _target_: ray.air.RunConfig
  progress_reporter:
    _target_: custom_utils.custom_reporter.CLIReporter
    parameter_columns: ${oc.dict.keys:hparams_search.param_space}
    metric_columns:
      - epoch
      - Batch_ID
      - loss
      - val_loss
      - val_score
      - best_val_score
      - progress_of_epoch
  local_dir: ${log_dir}/${hydra:sweep.subdir}
  verbose: 2
  # callbacks:
  #   - _target_: ray.air.integrations.wandb.WandbLoggerCallback
  #     api_key: ${api_key}
  #     project: ${logging.setup.project}
