#param_space:
lr: 0.0001
batch_size: 32
weight_decay: 0.0001 # 1e-4
asl_gamma_neg: 2
asl_ps_factor: 0.1
ra_num_ops: 2
ra_magnitude: 9

###user modifiable configs###
ckpt_name: "best_saved.pth"
epochs: 3
seed: 12345
num_workers: 2
num_classes: 5

log_dir: ./logs/train/${now:%Y-%m-%d_%H-%M-%S}
save_dir: ${log_dir}/${hydra:job.override_dirname}

###ray###
num_samples: 3

###WandB###
project_name:  # subject to change

###Hydra Configs###
hydra:
  runtime:
    cwd: .
  run:
    dir: ${save_dir}

  sweep:
    dir: ${log_dir}
    subdir: ${hydra.job.override_dirname}

###defaults###
defaults:
  - _self_
  - Dataset: CheXpert
  - Dataloader: Dataloader
  - optimizer: Adam
  - loss: Multi_Soft_Margin
  - model: densenet             # Select training model. 'resnet': ResNet50, 'densenet': DenseNet121, 'swin_transformer': swinv2_small_224
  - hparams_search: none
  - logging: null
  - conditional_train: null     # Conditional training option. 'conditional' or 'null'

####experimental
print_config: False
use_amp: True # Automatic mixed precision option. True or False
stop_patience: 5
