#param_space:
rotate_degree: 15
lr: 0.0001
batch_size: 32
weight_decay: 0.0001    # 1e-4

###user modifiable configs###
ckpt_name: "best_saved.pth"
epochs: 1
seed: 12345
num_workers: 2
num_classes: 5
log_dir: ./logs/${now:%Y-%m-%d_%H-%M-%S}
save_dir: ${log_dir}/${hydra:job.override_dirname}

###ray###
num_samples: 3

###WandB###
project_name:   # subject to change

###Hydra Configs###
hydra:
  runtime:
    cwd: .
  run:
    dir: ${save_dir}

  sweep:
    dir: ${log_dir}
    subdir: ${hydra.job.override_dirname}

###defaults###
defaults:
  - _self_
  - Dataset: CheXpert
  - Dataloader: Dataloader
  - optimizer: adam
  - loss: Multi_Soft_Margin
  - model: densenet
  - hparams_search: none
  - logging: wandb
  - conditional_train: none    # Conditional training option. 'default' or 'none'

####experimental
print_config: False
use_amp: True    # Automatic mixed precision option. True or False
