#### config/loader.yaml

train:
        batch_size: ${batch_size}
        num_workers: 2
        drop_last: False
        shuffle: True

test:
        batch_size: ${batch_size}
        num_workers: 2
        drop_last: False
        shuffle: False