#config/ray/raytune.yaml
param_space: 
        lr: 
                _target_: ray.tune.loguniform
                lower: 0.0001
                upper: 0.1
        batch_size:
                _target_: ray.tune.choice
                categories:
                        - 64
                        - 128
        weight_decay:
                _target_: ray.tune.loguniform
                lower: 0.0001
                upper: 0.1

search_alg:
        _target_: ray.tune.search.hyperopt.HyperOptSearch
        metric: loss
        mode: min

scheduler:
        _target_: ray.tune.schedulers.ASHAScheduler
        metric: loss
        mode: min

reporter: 
        _target_: custom_utils.custom_reporter.TrialTerminationReporter
        parameter_columns:
                - lr
                - batch_size
        metric_columns:
                - loss
                - val_loss
                - val_score
                - current_epoch
                - progress_of_epoch

run_config:
        _target_: ray.air.RunConfig
        #progress_reporter: reporter
        local_dir: "./ray_logs/"
        name: "test_experiment"
        verbose: 2

num_samples: ${num_samples}
local_dir: './ray_logs/'
name: 'test_experiment'