#search spaxce for ray

# search_space = {
#         "lr": tune.loguniform(1e-4, 1e-1),
#         #"batch_size": tune.choice([128, 256, 512])
#     }

lr:
        _target_: ray.tune.loguniform
        lower: 1e-4
        upper: 1e-1
