#### config/loader.yaml

train:
  #batch_size: 128
  num_workers: ${num_workers}
  drop_last: True
  shuffle: True

test:
  #batch_size: 128
  num_workers: ${num_workers}
  drop_last: False
  shuffle: False
