#### config/loader.yaml

conditional_train:
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  drop_last: True
  shuffle: True

train:
  _target_: torch.utils.data.DataLoader
  dataset: 
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  drop_last: True
  shuffle: True

valid:
  _target_: torch.utils.data.DataLoader
  dataset: 
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  drop_last: False
  shuffle: False

test:
  _target_: torch.utils.data.DataLoader
  dataset: 
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  drop_last: False
  shuffle: False
