#### config/loader.yaml

conditional_train:
  batch_size: 64
  num_workers: ${num_workers}
  drop_last: True
  shuffle: True

train:
  #batch_size: 128
  num_workers: ${num_workers}
  drop_last: True
  shuffle: True

valid:
  #batch_size: 128
  num_workers: ${num_workers}
  drop_last: False
  shuffle: False

test:
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  drop_last: False
  shuffle: False
