execute_mode: default

#param_space:
rotate_degree: 15
lr: 0.0001
batch_size: 128
weight_decay: 0.0001 #1

epochs: 2
seed: 12345
num_workers: 2
num_classes: 5


model:
  _target_: timm.create_model
  model_name: densenet121
  pretrained: True
  num_classes: ${num_classes}

loss:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam

  lr: None # ${lr}
  betas: 
          - 0.9 
          - 0.99
  eps: 1e-8
  weight_decay: 1 # 1e-4

ckpt_name: "pre_best_saved.pth"