defaults:
  - _self_
  - epochs: 2
  - seed: 12345
  - num_workers: 2
  - num_classes: 5

  - Dataset: CheXpert
  - Dataloader: Dataloader
  - optimizer: adam
  - loss: CE
  - model: densenet
  - mode: default   # raytune

  - ckpt_name: "pre_best_saved.pth"