#user modifiable configs

ckpt_name: 'best_saved.pth'
epochs: 5
lr: 0.0001
batch_size: 64
seed: 777


#defaults

defaults:
        - _self_
        - Dataset: CheXpert
        - Dataloader: Dataloader 
        - optimizer: adam
        - loss: BCE
        - model: resnet