#user modifiable configs

ckpt_name: 'best_saved.pth'
epochs: 5
lr: 0.1
batch_size: 64
seed: 777
num_classes: 5


#defaults

defaults:
        - _self_
        - Dataset: CheXpert
        - Dataloader: Dataloader 
        - optimizer: pesg
        - loss: AUCM
        - model: resnet